export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SHOW_HIDE_DATE_PICKER = 'SHOW_HIDE_DATE_PICKER';
export const DECREMENT_MONTH = 'DECREMENT_MONTH';
export const INCREMENT_MONTH = 'INCREMENT_MONTH';
export const CHANGE_MONTH = 'CHANGE_MONTH';
export const CHANGE_START_DATE = 'CHANGE_START_DATE';

